
name: mathnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.9
  - cudatoolkit=11.1
  - torchvision=0.10
  - numpy=1.21
  - matplotlib=3.4
  - scikit-learn=0.24
  - ipython
  - ipykernel
  - jupyterlab
  - ipywidgets
  - tqdm
  - nb_conda_kernels